### PR TITLE
Fix SecurityPolicy on Windows

### PR DESCRIPTION
**Pull request by Mobmaker55**
This fixes the issues with Windows' SecurityPolicy check.

### CODE REVIEW

**Comment by Mobmaker55** [comment]
The docs are all ready to go!

**Comment by safinsingh** [comment]
Thanks! We'll review it ASAP. In the meantime, would you mind merging `upstream/master` into your fork?

**Comment by Mobmaker55** [comment]
I don't get why it's saying there are conflicts, everything is merged up to date ;-;

**Comment by Mobmaker55** [comment]
ok I have to close this so I can make a new repo, I'll reopen this in (hopefully) an hour

**Pull request closed without merging**
