### PR TITLE
Change Package to Program

### PR DESCRIPTION
**Pull request by Mobmaker55**
Consolidated naming scheme so we don't have two different words.
I get that Windows has `programs` and Linux has `packages` but `programs` fits better than `packages` for all OS'es in my opinion. `packages` doesn't sound right at all with Windows, but `programs` on Linux still sounds fine.

### CODE REVIEW

**Comment by Mobmaker55** [comment]
Apparently since this PR was open it just added everything I was working on, so this also now includes my work for issue [106](https://github.com/elysium-suite/aeacus/issues/106).

**Comment by safinsingh** [comment]
1. I'd prefer if you made this a separate PR. You can create a branch off of `Mobmaker55:master` and send in a pull request from that branch. We'll merge that PR once we merge this one into master and master is merged into your other PR.
2. Could you please add the `.idea` folder to `.gitignore`? We don't want those files in version control.

Thanks for the contribution!

**Comment by Mobmaker55** [comment]
i removed the IDE folder and the securityPolicy fix.

**Comment by safinsingh** [comment]
Thanks! This looks ready to merge. @sourque feel free to take another look if you'd like.

**Review by safinsingh — APPROVED** [review]

**Review by sourque — APPROVED** [review]

**Pull request merged**
