### PR TITLE
Dab

### LINKED ISSUE #90: CI/Productivity
There's a couple productivity tools we could add like `goreleaser` and `golangci-lint`. We should also dockerize our local CI testing to make it available to people who don't have `go` installed (as in just wrap `golangci-lint`, `goreleaser`, build, testing, etc in a `Dockerfile`). This way, we can allow others to simulate our CI without having to actually install the tooling for an open-source contribution.

### PR DESCRIPTION
**Pull request by safinsingh**
@sourque please dab on this
partially resolves #90

### CODE REVIEW

**Review by sourque — COMMENTED** [review]
Thanks Lint Lord. Having a log function for the Wats would be great. Also, we're not using garble anymore?

**Comment by safinsingh** [comment]
Window 10 no like garble

**Comment by safinsingh** [comment]
Wat func coming soon wen brain >5%

**Review by sourque — APPROVED** [review]
:ok_hand:  :100: :ok_hand:

**Comment by safinsingh** [comment]
rot

**Comment by safinsingh** [comment]
can you merge

**Pull request merged**
