### PR TITLE
Auto-trusting of .desktop files for Linux release

### PR DESCRIPTION
**Pull request by Mobmaker55**
This is currently not working on Ubuntu 20.04 but it is on 18.04...

### CODE REVIEW

**Comment by safinsingh** [comment]
can you move the loop into go code? it's just cleaner

**Comment by Mobmaker55** [comment]
@safinsingh it's not even working right at all right now ( on 20.04 )* -- I'm trying to fix it for Ubuntu 20.04

**Comment by s3ck** [comment]
Is this issue still open?

**Comment by StevenEck** [comment]
Is this issue still open?

**Comment by Mobmaker55** [comment]
@StevenEck yes, it is still being worked on. We just temporarily had to table it while we worked on the v2.0 rework.
This PR will likely be done before July 17

**Comment by Mobmaker55** [comment]
@StevenEck Okay... so this is not going to be able to work as far as I am aware-- there is no way within the scope of our project to trust the .desktop files. Your best bet is just to right-click on the files and have that be that. It's a file metadata issue that nobody has been able to figure out so far. 
Sorry about this... we will let you know if we find a fix though!

**Pull request closed without merging**
