### PR TITLE
New Windows Checks

### PR DESCRIPTION
**Pull request by Mobmaker55**
`ProgramVersion` and `ProgramVersionNot`, along with the documentation for both.

### CODE REVIEW

**Comment by Mobmaker55** [comment]
You can remove `.deepsource.toml`, the bot does it automatically, and I forgot that it was in my fork when I committed.

**Comment by safinsingh** [comment]
@elysium-suite/windows please take a look at this

**Comment by sourque** [comment]
I thought it might be a bit better to use two-letter codes (kind of like Bash does) instead of the numbers. I also made the package selection operate on a substring rather than exact match, because often the package name on Windows is something like "Mozilla Firefox 87.0" which kind of... defeats the purpose. Let me know what you think!

**Comment by safinsingh** [comment]
@Mobmaker55 I think it'd be a better idea to put your last commit in a separate PR so we can have a separate discussion about it.

**Comment by Mobmaker55** [comment]
@safinsingh I think that it needs to be done at least for now because as of commit [e4da86a4](https://github.com/elysium-suite/aeacus/pull/101/commits/e4d86a4f0aee5fa22bb478a73a11765536b6381a) the `PackageVersion` for Linux was replaced with `ProgramVersion`, and to further consolidate I was just going to rename `PackageInstalled` to `ProgramInstalled`.

**Comment by safinsingh** [comment]
Sure, but since it's unrelated to this PR, I'd prefer if you made it separately for organizational purposes :)

**Comment by Mobmaker55** [comment]
Well in that case, that's it for this PR I think, if everyone likes the addition and fixes from sourque.

**Comment by safinsingh** [comment]
Awesome, thanks for your work on this!

**Pull request merged**
